<?php
/**
 * Implements hook_help().
 *
 * Displays help and module information. Which we don't have. So update later.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function nursing_help($path, $arg) {
  switch ($path) {
    case "admin/help#nursing":
      return t("You weren't supposed to look here. I can't help you."); 
      break; 
  }
}

/*
This adds a menu link for the form defined below.
*/
function nursing_menu() {
  $items = array();

  $items['nursing/add'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Add an event', //page title
    'description' => 'This is the form that you will add an event or request one.',
    'page callback' => 'drupal_get_form', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
    'page arguments' => array('nursing_form'), //put the name of the form here
    'access callback' => TRUE
  );
  $items['nursing/selectroom'] = array( 
    'title' => 'Pick your room', //page title
    'description' => 'You will select a room on this page.',
    'page callback' => 'drupal_get_form', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
    'page arguments' => array('nursing_second_form'), //put the name of the form here
    'access callback' => TRUE
  );
  return $items;
}
/*
This creates the form.
NOTE! For the two select boxes you MUST define fields with these names exactly.
To do this, go to some random bullcrap content type that you don't use (make one if you have to)
Click manage fields
On the Add New Field line, select "Term Reference" and then name each one the name of the field (courses, class_type)
Hit save and on the next popup, select "Course" or "Class Type " 
*/
function nursing_form($form, &$form_state) {
     $form['title'] = array(
    '#type' => 'textfield', 
    '#title' => 'Title:',
    '#required' => TRUE, 
  );
  
 $form['type'] = array(
    '#type' => 'select', 
    '#title' => 'What type of event is this?',
	'#options' => taxonomy_allowed_values(field_info_field('field_class_type')), 
    '#required' => TRUE, 
  );
  
   $form['date'] = array(
    '#type' => 'date', 
    '#title' => 'When? Note: If you are entering a course that will repeat weekly, please enter the first day. You will be able to pick repeat options later.',
    '#required' => TRUE, 
  );

   $form['course'] = array(
    '#type' => 'select', 
    '#title' => 'For what course is this event? (Optional)',
	'#options' => taxonomy_allowed_values(field_info_field('field_courses')),
    '#required' => FALSE, 
  );
   $form['crn'] = array(
    '#type' => 'select', 
    '#title' => 'For what course is this event? (Optional)',
	'#options' => 'to be added later',
    '#required' => FALSE, 
  );

   $form['capacity'] = array(
    '#type' => 'textfield', 
    '#title' => 'How many seats do you need? (Optional)',
    '#size' => 5,
    '#maxlength' => 5,
    '#required' => FALSE, 
  );

  
   $form['notes'] = array(
    '#type' => 'textarea', 
    '#title' => 'Notes: (Optional)',
    '#required' => FALSE, 
  );

  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Select room'),
  );
  
  return $form;
}
function nursing_form_validate($form, &$form_state) {

}
/*
submit form action
*/
function nursing_form_submit($form, &$form_state) {
	
	$type = $form_state['values']['type'];
	$course = $form_state['values']['course'];
	$capacity = $form_state['values']['capacity'];
	$notes = $form_state['values']['notes'];
	$date = $form_state['values']['date'];

    $url = 'nursing/selectroom';

    $options = array(
      'query' => array(
        'type' => $type,
		'course' => $course,
		'capacity' => $capacity,
		'notes' => $notes,
		'date' => $date,
      ),
    );


    $form_state['redirect'] = array(
      $url,
      $options,
    );
}

/*
attempt at second form
*/
function nursing_second_form($form, &$form_state) {
  
  
echo $_GET['type'];
//print_r(module_invoke('room_reservations', 'room_reservations', 2, 21));

  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Submit request'),
  );
  
  return $form;
}



function nursing_second_form_submit($form, &$form_state) {
	
}